#
# Makefile for breath led devices
#

obj-$(CONFIG_OPPO_DEVICE_FIND7)		+= shineled_driver_find7.o
obj-$(CONFIG_OPPO_DEVICE_FIND7OP)		+= shineled_driver_find7op.o
obj-$(CONFIG_OPPO_DEVICE_FIND7WX)		+= shineled_driver_find7.o