ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ flash/ eeprom/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
