ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo_n3/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
