# cpuquit governor
obj-$(CONFIG_CPUQUIET_GOVERNOR_BALANCED)	+= balanced.o
obj-$(CONFIG_CPUQUIET_GOVERNOR_RUNNABLE)	+= runnable_threads.o
obj-$(CONFIG_CPUQUIET_GOVERNOR_RQ_STATS)	    += rq_stats.o
obj-$(CONFIG_CPUQUIET_GOVERNOR_LOAD_STATS)	    += load_stats.o
