#
# Makefile for nfc devices

# 15 Oct 2013, Yuyi <oppo@Independent Group>
# Rewritten to use pn544 driver.

obj-$(CONFIG_OPPO_DEVICE_FIND7)		+= pn544.o
obj-$(CONFIG_OPPO_DEVICE_FIND7OP)		+= pn544_op.o
obj-$(CONFIG_OPPO_DEVICE_FIND7OP)		+= p61.o
obj-$(CONFIG_OPPO_DEVICE_FIND7WX)		+= pn544.o
#obj-$(CONFIG_NFC_PN533)		+= pn533.o
#obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o

#ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
