ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
