ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
