ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oppo/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
